version: "3.9"

services:
  db: # container that contains MariaDB only without nginx
    container_name: db
    restart: unless-stopped # restarts in case of a crash
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-default_root_pwd}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress_db}
      - MYSQL_USER=${MYSQL_USER:-wordpress_usr}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-default_password}
    networks:
      - docker-network
  wordpress: # container that contains WordPress + php-fpm
    container_name: wordpress
    restart: unless-stopped # restarts in case of a crash
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mariadb}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress_db}
      - MYSQL_USER=${MYSQL_USER:-wordpress_usr}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-default_password}
    depends_on:
      - db
    links:
      - db
    networks:
      - docker-network
  nginx: # container that contains NGINX with TLSv1.2 or TLSv1.3 only
    container_name: nginx
    restart: unless-stopped # restarts in case of a crash
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    links:
      - wordpress
    networks:
      - docker-network


volumes:
  db_data: # volume that contains the WordPress database
    driver_opts:
      device: '/home/llalba/data'
  wordpress_data: # 2d volume that contains the WordPress website files
    driver_opts:
      device: '/home/llalba/data'

networks:
  docker-network: # establishes the connection between the containers
